package com.wipro.ats.bdre.md.setup.beans;
// Generated Dec 21, 2015 11:26:14 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.Date;

/**
 * BatchConsumpQueue generated by hbm2java
 */
@Entity
@Table(name="BATCH_CONSUMP_QUEUE"
    ,schema="BDRE"
    ,catalog="BDRE"
)
public class BatchConsumpQueue  implements java.io.Serializable {


     private Long queueId;
     private Long sourceBatchId;
     private Long targetBatchId;
     private Date insertTs;
     private Integer sourceProcessId;
     private Date startTs;
     private Date endTs;
     private Integer batchState;
     private String batchMarking;
     private Integer processId;

    public BatchConsumpQueue() {
    }

	
    public BatchConsumpQueue(Long sourceBatchId, Date insertTs, Integer batchState, Integer processId) {
        this.sourceBatchId = sourceBatchId;
        this.insertTs = insertTs;
        this.batchState = batchState;
        this.processId = processId;
    }
    public BatchConsumpQueue(Long sourceBatchId, Long targetBatchId, Date insertTs, Integer sourceProcessId, Date startTs, Date endTs, Integer batchState, String batchMarking, Integer processId) {
       this.sourceBatchId = sourceBatchId;
       this.targetBatchId = targetBatchId;
       this.insertTs = insertTs;
       this.sourceProcessId = sourceProcessId;
       this.startTs = startTs;
       this.endTs = endTs;
       this.batchState = batchState;
       this.batchMarking = batchMarking;
       this.processId = processId;
    }
   
     @Id 
    
    @Column(name="QUEUE_ID", unique=true, nullable=false)
    public Long getQueueId() {
        return this.queueId;
    }
    
    public void setQueueId(Long queueId) {
        this.queueId = queueId;
    }
    
    @Column(name="SOURCE_BATCH_ID", nullable=false)
    public Long getSourceBatchId() {
        return this.sourceBatchId;
    }
    
    public void setSourceBatchId(Long sourceBatchId) {
        this.sourceBatchId = sourceBatchId;
    }
    
    @Column(name="TARGET_BATCH_ID")
    public Long getTargetBatchId() {
        return this.targetBatchId;
    }
    
    public void setTargetBatchId(Long targetBatchId) {
        this.targetBatchId = targetBatchId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="INSERT_TS", nullable=false, length=23)
    public Date getInsertTs() {
        return this.insertTs;
    }
    
    public void setInsertTs(Date insertTs) {
        this.insertTs = insertTs;
    }
    
    @Column(name="SOURCE_PROCESS_ID")
    public Integer getSourceProcessId() {
        return this.sourceProcessId;
    }
    
    public void setSourceProcessId(Integer sourceProcessId) {
        this.sourceProcessId = sourceProcessId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="START_TS", length=23)
    public Date getStartTs() {
        return this.startTs;
    }
    
    public void setStartTs(Date startTs) {
        this.startTs = startTs;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="END_TS", length=23)
    public Date getEndTs() {
        return this.endTs;
    }
    
    public void setEndTs(Date endTs) {
        this.endTs = endTs;
    }
    
    @Column(name="BATCH_STATE", nullable=false)
    public Integer getBatchState() {
        return this.batchState;
    }
    
    public void setBatchState(Integer batchState) {
        this.batchState = batchState;
    }
    
    @Column(name="BATCH_MARKING", length=45)
    public String getBatchMarking() {
        return this.batchMarking;
    }
    
    public void setBatchMarking(String batchMarking) {
        this.batchMarking = batchMarking;
    }
    
    @Column(name="PROCESS_ID", nullable=false)
    public Integer getProcessId() {
        return this.processId;
    }
    
    public void setProcessId(Integer processId) {
        this.processId = processId;
    }




}


