package com.wipro.ats.bdre.md.setup.beans;
// Generated Dec 21, 2015 11:26:14 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Docidsdb generated by hbm2java
 */
@Entity
@Table(name="DOCIDSDB"
    ,schema="BDRE"
    ,catalog="BDRE"
)
public class Docidsdb  implements java.io.Serializable {


     private Long docid;
     private String url;

    public Docidsdb() {
    }

    public Docidsdb(String url) {
       this.url = url;
    }
   
     @Id 
    
    @Column(name="DOCID", unique=true, nullable=false)
    public Long getDocid() {
        return this.docid;
    }
    
    public void setDocid(Long docid) {
        this.docid = docid;
    }
    
    @Column(name="URL", length=3000)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }




}


