package com.wipro.ats.bdre.md.setup.beans;
// Generated Dec 21, 2015 11:26:14 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EtlDriver generated by hbm2java
 */
@Entity
@Table(name="ETL_DRIVER"
    ,schema="BDRE"
    ,catalog="BDRE"
)
public class EtlDriver  implements java.io.Serializable {


     private Integer etlProcessId;
     private Integer rawTableId;
     private Integer baseTableId;
     private Short insertType;
     private Boolean dropRaw;
     private Integer rawViewId;

    public EtlDriver() {
    }

	
    public EtlDriver(Integer etlProcessId, Integer rawTableId, Integer rawViewId) {
        this.etlProcessId = etlProcessId;
        this.rawTableId = rawTableId;
        this.rawViewId = rawViewId;
    }
    public EtlDriver(Integer etlProcessId, Integer rawTableId, Integer baseTableId, Short insertType, Boolean dropRaw, Integer rawViewId) {
       this.etlProcessId = etlProcessId;
       this.rawTableId = rawTableId;
       this.baseTableId = baseTableId;
       this.insertType = insertType;
       this.dropRaw = dropRaw;
       this.rawViewId = rawViewId;
    }
   
     @Id 
    
    @Column(name="ETL_PROCESS_ID", unique=true, nullable=false)
    public Integer getEtlProcessId() {
        return this.etlProcessId;
    }
    
    public void setEtlProcessId(Integer etlProcessId) {
        this.etlProcessId = etlProcessId;
    }
    
    @Column(name="RAW_TABLE_ID", nullable=false)
    public Integer getRawTableId() {
        return this.rawTableId;
    }
    
    public void setRawTableId(Integer rawTableId) {
        this.rawTableId = rawTableId;
    }
    
    @Column(name="BASE_TABLE_ID")
    public Integer getBaseTableId() {
        return this.baseTableId;
    }
    
    public void setBaseTableId(Integer baseTableId) {
        this.baseTableId = baseTableId;
    }
    
    @Column(name="INSERT_TYPE")
    public Short getInsertType() {
        return this.insertType;
    }
    
    public void setInsertType(Short insertType) {
        this.insertType = insertType;
    }
    
    @Column(name="DROP_RAW")
    public Boolean getDropRaw() {
        return this.dropRaw;
    }
    
    public void setDropRaw(Boolean dropRaw) {
        this.dropRaw = dropRaw;
    }
    
    @Column(name="RAW_VIEW_ID", nullable=false)
    public Integer getRawViewId() {
        return this.rawViewId;
    }
    
    public void setRawViewId(Integer rawViewId) {
        this.rawViewId = rawViewId;
    }




}


