package com.wipro.ats.bdre.md.setup.beans;
// Generated Dec 21, 2015 11:26:14 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * EtlstepId generated by hbm2java
 */
@Embeddable
public class EtlstepId  implements java.io.Serializable {


     private Long serialNumber;
     private String uuid;

    public EtlstepId() {
    }

    public EtlstepId(Long serialNumber, String uuid) {
       this.serialNumber = serialNumber;
       this.uuid = uuid;
    }
   

    @Column(name="SERIAL_NUMBER", nullable=false)
    public Long getSerialNumber() {
        return this.serialNumber;
    }
    
    public void setSerialNumber(Long serialNumber) {
        this.serialNumber = serialNumber;
    }

    @Column(name="UUID", nullable=false, length=128)
    public String getUuid() {
        return this.uuid;
    }
    
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof EtlstepId) ) return false;
		 EtlstepId castOther = ( EtlstepId ) other; 
         
		 return ( (this.getSerialNumber()==castOther.getSerialNumber()) || ( this.getSerialNumber()!=null && castOther.getSerialNumber()!=null && this.getSerialNumber().equals(castOther.getSerialNumber()) ) )
 && ( (this.getUuid()==castOther.getUuid()) || ( this.getUuid()!=null && castOther.getUuid()!=null && this.getUuid().equals(castOther.getUuid()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getSerialNumber() == null ? 0 : this.getSerialNumber().hashCode() );
         result = 37 * result + ( getUuid() == null ? 0 : this.getUuid().hashCode() );
         return result;
   }   


}


