package com.wipro.ats.bdre.md.setup.beans;
// Generated Dec 21, 2015 11:26:14 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;

/**
 * Etlstep generated by hbm2java
 */
@Entity
@Table(name="ETLSTEP"
    ,schema="BDRE"
    ,catalog="BDRE"
)
public class Etlstep  implements java.io.Serializable {


     private EtlstepId id;
     private Integer busDomainId;
     private String processName;
     private String description;
     private String baseTableName;
     private String rawTableName;
     private String rawViewName;
     private String baseDbName;
     private String rawDbName;
     private String baseTableDdl;
     private String rawTableDdl;
     private String rawViewDdl;
     private String rawPartitionCol;
     private Boolean dropRaw;
     private Integer enqId;
     private String columnInfo;
     private String serdeProperties;
     private String tableProperties;
     private String inputFormat;

    public Etlstep() {
    }

	
    public Etlstep(EtlstepId id, Integer busDomainId, String processName, String description) {
        this.id = id;
        this.busDomainId = busDomainId;
        this.processName = processName;
        this.description = description;
    }
    public Etlstep(EtlstepId id, Integer busDomainId, String processName, String description, String baseTableName, String rawTableName, String rawViewName, String baseDbName, String rawDbName, String baseTableDdl, String rawTableDdl, String rawViewDdl, String rawPartitionCol, Boolean dropRaw, Integer enqId, String columnInfo, String serdeProperties, String tableProperties, String inputFormat) {
       this.id = id;
       this.busDomainId = busDomainId;
       this.processName = processName;
       this.description = description;
       this.baseTableName = baseTableName;
       this.rawTableName = rawTableName;
       this.rawViewName = rawViewName;
       this.baseDbName = baseDbName;
       this.rawDbName = rawDbName;
       this.baseTableDdl = baseTableDdl;
       this.rawTableDdl = rawTableDdl;
       this.rawViewDdl = rawViewDdl;
       this.rawPartitionCol = rawPartitionCol;
       this.dropRaw = dropRaw;
       this.enqId = enqId;
       this.columnInfo = columnInfo;
       this.serdeProperties = serdeProperties;
       this.tableProperties = tableProperties;
       this.inputFormat = inputFormat;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="serialNumber", column=@Column(name="SERIAL_NUMBER", nullable=false) ), 
        @AttributeOverride(name="uuid", column=@Column(name="UUID", nullable=false, length=128) ) } )
    public EtlstepId getId() {
        return this.id;
    }
    
    public void setId(EtlstepId id) {
        this.id = id;
    }
    
    @Column(name="BUS_DOMAIN_ID", nullable=false)
    public Integer getBusDomainId() {
        return this.busDomainId;
    }
    
    public void setBusDomainId(Integer busDomainId) {
        this.busDomainId = busDomainId;
    }
    
    @Column(name="PROCESS_NAME", nullable=false, length=256)
    public String getProcessName() {
        return this.processName;
    }
    
    public void setProcessName(String processName) {
        this.processName = processName;
    }
    
    @Column(name="DESCRIPTION", nullable=false, length=2048)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    @Column(name="BASE_TABLE_NAME", length=45)
    public String getBaseTableName() {
        return this.baseTableName;
    }
    
    public void setBaseTableName(String baseTableName) {
        this.baseTableName = baseTableName;
    }
    
    @Column(name="RAW_TABLE_NAME", length=45)
    public String getRawTableName() {
        return this.rawTableName;
    }
    
    public void setRawTableName(String rawTableName) {
        this.rawTableName = rawTableName;
    }
    
    @Column(name="RAW_VIEW_NAME", length=45)
    public String getRawViewName() {
        return this.rawViewName;
    }
    
    public void setRawViewName(String rawViewName) {
        this.rawViewName = rawViewName;
    }
    
    @Column(name="BASE_DB_NAME", length=45)
    public String getBaseDbName() {
        return this.baseDbName;
    }
    
    public void setBaseDbName(String baseDbName) {
        this.baseDbName = baseDbName;
    }
    
    @Column(name="RAW_DB_NAME", length=45)
    public String getRawDbName() {
        return this.rawDbName;
    }
    
    public void setRawDbName(String rawDbName) {
        this.rawDbName = rawDbName;
    }
    
    @Column(name="BASE_TABLE_DDL", length=2048)
    public String getBaseTableDdl() {
        return this.baseTableDdl;
    }
    
    public void setBaseTableDdl(String baseTableDdl) {
        this.baseTableDdl = baseTableDdl;
    }
    
    @Column(name="RAW_TABLE_DDL", length=2048)
    public String getRawTableDdl() {
        return this.rawTableDdl;
    }
    
    public void setRawTableDdl(String rawTableDdl) {
        this.rawTableDdl = rawTableDdl;
    }
    
    @Column(name="RAW_VIEW_DDL", length=2048)
    public String getRawViewDdl() {
        return this.rawViewDdl;
    }
    
    public void setRawViewDdl(String rawViewDdl) {
        this.rawViewDdl = rawViewDdl;
    }
    
    @Column(name="RAW_PARTITION_COL", length=45)
    public String getRawPartitionCol() {
        return this.rawPartitionCol;
    }
    
    public void setRawPartitionCol(String rawPartitionCol) {
        this.rawPartitionCol = rawPartitionCol;
    }
    
    @Column(name="DROP_RAW")
    public Boolean getDropRaw() {
        return this.dropRaw;
    }
    
    public void setDropRaw(Boolean dropRaw) {
        this.dropRaw = dropRaw;
    }
    
    @Column(name="ENQ_ID")
    public Integer getEnqId() {
        return this.enqId;
    }
    
    public void setEnqId(Integer enqId) {
        this.enqId = enqId;
    }
    
    @Column(name="COLUMN_INFO", length=2048)
    public String getColumnInfo() {
        return this.columnInfo;
    }
    
    public void setColumnInfo(String columnInfo) {
        this.columnInfo = columnInfo;
    }
    
    @Column(name="SERDE_PROPERTIES", length=2048)
    public String getSerdeProperties() {
        return this.serdeProperties;
    }
    
    public void setSerdeProperties(String serdeProperties) {
        this.serdeProperties = serdeProperties;
    }
    
    @Column(name="TABLE_PROPERTIES", length=2048)
    public String getTableProperties() {
        return this.tableProperties;
    }
    
    public void setTableProperties(String tableProperties) {
        this.tableProperties = tableProperties;
    }
    
    @Column(name="INPUT_FORMAT", length=2048)
    public String getInputFormat() {
        return this.inputFormat;
    }
    
    public void setInputFormat(String inputFormat) {
        this.inputFormat = inputFormat;
    }




}


