package com.wipro.ats.bdre.md.setup.beans;
// Generated Dec 21, 2015 11:26:14 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ExecStatus generated by hbm2java
 */
@Entity
@Table(name="EXEC_STATUS"

)
public class ExecStatus  implements java.io.Serializable {


     private Integer execStateId;
     private String description;

    public ExecStatus() {
    }

    public ExecStatus(Integer execStateId, String description) {
       this.execStateId = execStateId;
       this.description = description;
    }
   
     @Id 
    
    @Column(name="EXEC_STATE_ID", unique=true, nullable=false)
    public Integer getExecStateId() {
        return this.execStateId;
    }
    
    public void setExecStateId(Integer execStateId) {
        this.execStateId = execStateId;
    }
    
    @Column(name="DESCRIPTION", nullable=false, length=45)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


