package com.wipro.ats.bdre.md.setup.beans;
// Generated Dec 21, 2015 11:26:14 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Embeddable;
import java.util.Date;

/**
 * FileId generated by hbm2java
 */
@Embeddable
public class FileId  implements java.io.Serializable {


     private Long batchId;
     private Integer serverId;
     private String path;
     private Long fileSize;
     private String fileHash;
     private Date creationTs;

    public FileId() {
    }

	
    public FileId(Long batchId, Integer serverId, String path, Long fileSize, Date creationTs) {
        this.batchId = batchId;
        this.serverId = serverId;
        this.path = path;
        this.fileSize = fileSize;
        this.creationTs = creationTs;
    }
    public FileId(Long batchId, Integer serverId, String path, Long fileSize, String fileHash, Date creationTs) {
       this.batchId = batchId;
       this.serverId = serverId;
       this.path = path;
       this.fileSize = fileSize;
       this.fileHash = fileHash;
       this.creationTs = creationTs;
    }
   

    @Column(name="BATCH_ID", nullable=false)
    public Long getBatchId() {
        return this.batchId;
    }
    
    public void setBatchId(Long batchId) {
        this.batchId = batchId;
    }

    @Column(name="SERVER_ID", nullable=false)
    public Integer getServerId() {
        return this.serverId;
    }
    
    public void setServerId(Integer serverId) {
        this.serverId = serverId;
    }

    @Column(name="PATH", nullable=false, length=256)
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }

    @Column(name="FILE_SIZE", nullable=false)
    public Long getFileSize() {
        return this.fileSize;
    }
    
    public void setFileSize(Long fileSize) {
        this.fileSize = fileSize;
    }

    @Column(name="FILE_HASH", length=100)
    public String getFileHash() {
        return this.fileHash;
    }
    
    public void setFileHash(String fileHash) {
        this.fileHash = fileHash;
    }

    @Column(name="CREATION_TS", nullable=false, length=23)
    public Date getCreationTs() {
        return this.creationTs;
    }
    
    public void setCreationTs(Date creationTs) {
        this.creationTs = creationTs;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof FileId) ) return false;
		 FileId castOther = ( FileId ) other; 
         
		 return ( (this.getBatchId()==castOther.getBatchId()) || ( this.getBatchId()!=null && castOther.getBatchId()!=null && this.getBatchId().equals(castOther.getBatchId()) ) )
 && ( (this.getServerId()==castOther.getServerId()) || ( this.getServerId()!=null && castOther.getServerId()!=null && this.getServerId().equals(castOther.getServerId()) ) )
 && ( (this.getPath()==castOther.getPath()) || ( this.getPath()!=null && castOther.getPath()!=null && this.getPath().equals(castOther.getPath()) ) )
 && ( (this.getFileSize()==castOther.getFileSize()) || ( this.getFileSize()!=null && castOther.getFileSize()!=null && this.getFileSize().equals(castOther.getFileSize()) ) )
 && ( (this.getFileHash()==castOther.getFileHash()) || ( this.getFileHash()!=null && castOther.getFileHash()!=null && this.getFileHash().equals(castOther.getFileHash()) ) )
 && ( (this.getCreationTs()==castOther.getCreationTs()) || ( this.getCreationTs()!=null && castOther.getCreationTs()!=null && this.getCreationTs().equals(castOther.getCreationTs()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getBatchId() == null ? 0 : this.getBatchId().hashCode() );
         result = 37 * result + ( getServerId() == null ? 0 : this.getServerId().hashCode() );
         result = 37 * result + ( getPath() == null ? 0 : this.getPath().hashCode() );
         result = 37 * result + ( getFileSize() == null ? 0 : this.getFileSize().hashCode() );
         result = 37 * result + ( getFileHash() == null ? 0 : this.getFileHash().hashCode() );
         result = 37 * result + ( getCreationTs() == null ? 0 : this.getCreationTs().hashCode() );
         return result;
   }   


}


