package com.wipro.ats.bdre.md.setup.beans;


import javax.persistence.*;
import java.util.Date;

/**
 * InstalledPlugins generated by hbm2java
 */
@Entity
@Table(name="INSTALLED_PLUGINS"
)
public class InstalledPlugins  implements java.io.Serializable {


    private String pluginUniqueId;
    private String pluginId;
    private String name;
    private String description;
    private String pluginVersion;
    private String author;
    private Date addTs;
    private String plugin;
    private Boolean uninstallable;

    public InstalledPlugins() {
    }


    public InstalledPlugins(String pluginUniqueId, String pluginId, String pluginVersion, Date addTs) {
        this.pluginUniqueId = pluginUniqueId;
        this.pluginId = pluginId;
        this.pluginVersion = pluginVersion;
        this.addTs = addTs;
    }
    @Id

    @Column(name="PLUGIN_UNIQUE_ID", unique=true, nullable=false, length=128)
    public String getPluginUniqueId() {
        return this.pluginUniqueId;
    }

    public void setPluginUniqueId(String pluginUniqueId) {
        this.pluginUniqueId = pluginUniqueId;
    }

    @Column(name="PLUGIN_ID", nullable=false, length=128)
    public String getPluginId() {
        return this.pluginId;
    }

    public void setPluginId(String pluginId) {
        this.pluginId = pluginId;
    }

    @Column(name="NAME", length=128)
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name="DESCRIPTION", length=128)
    public String getDescription() {
        return this.description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    @Column(name="PLUGIN_VERSION", nullable=false, length=128)
    public String getPluginVersion() {
        return this.pluginVersion;
    }

    public void setPluginVersion(String pluginVersion) {
        this.pluginVersion = pluginVersion;
    }

    @Column(name="AUTHOR", length=128)
    public String getAuthor() {
        return this.author;
    }

    public void setAuthor(String author) {
        this.author = author;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ADD_TS", nullable=false, length=19)
    public Date getAddTs() {
        return this.addTs;
    }

    public void setAddTs(Date addTs) {
        this.addTs = addTs;
    }

    @Column(name="PLUGIN", length=128)
    public String getPlugin() {
        return this.plugin;
    }

    public void setPlugin(String plugin) {
        this.plugin = plugin;
    }

    @Column(name="UNINSTALLABLE")
    public Boolean getUninstallable() {
        return this.uninstallable;
    }

    public void setUninstallable(Boolean uninstallable) {
        this.uninstallable = uninstallable;
    }




}


