package com.wipro.ats.bdre.md.setup.beans;
// Generated Dec 21, 2015 11:26:14 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.Date;

/**
 * LineageQuery generated by hbm2java
 */
@Entity
@Table(name="LINEAGE_QUERY"
    ,schema="BDRE"
    ,catalog="BDRE"
)
public class LineageQuery  implements java.io.Serializable {


     private String queryId;
     private String queryString;
     private Integer queryTypeId;
     private Date createTs;
     private Integer processId;
     private Long instanceExecId;

    public LineageQuery() {
    }

	
    public LineageQuery(String queryId, Integer queryTypeId) {
        this.queryId = queryId;
        this.queryTypeId = queryTypeId;
    }
    public LineageQuery(String queryId, String queryString, Integer queryTypeId, Date createTs, Integer processId, Long instanceExecId) {
       this.queryId = queryId;
       this.queryString = queryString;
       this.queryTypeId = queryTypeId;
       this.createTs = createTs;
       this.processId = processId;
       this.instanceExecId = instanceExecId;
    }
   
     @Id 
    
    @Column(name="QUERY_ID", unique=true, nullable=false, length=100)
    public String getQueryId() {
        return this.queryId;
    }
    
    public void setQueryId(String queryId) {
        this.queryId = queryId;
    }
    
    @Column(name="QUERY_STRING", length=4000)
    public String getQueryString() {
        return this.queryString;
    }
    
    public void setQueryString(String queryString) {
        this.queryString = queryString;
    }
    
    @Column(name="QUERY_TYPE_ID", nullable=false)
    public Integer getQueryTypeId() {
        return this.queryTypeId;
    }
    
    public void setQueryTypeId(Integer queryTypeId) {
        this.queryTypeId = queryTypeId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_TS", length=23)
    public Date getCreateTs() {
        return this.createTs;
    }
    
    public void setCreateTs(Date createTs) {
        this.createTs = createTs;
    }
    
    @Column(name="PROCESS_ID")
    public Integer getProcessId() {
        return this.processId;
    }
    
    public void setProcessId(Integer processId) {
        this.processId = processId;
    }
    
    @Column(name="INSTANCE_EXEC_ID")
    public Long getInstanceExecId() {
        return this.instanceExecId;
    }
    
    public void setInstanceExecId(Long instanceExecId) {
        this.instanceExecId = instanceExecId;
    }




}


