/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.wipro.ats.bdre.md.setup.beans;
// Generated Dec 21, 2015 11:26:14 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LineageNodeType generated by hbm2java
 */
@Entity
@Table(name="LINEAGE_NODE_TYPE"

)
public class LineageNodeType  implements java.io.Serializable {


     private Integer nodeTypeId;
     private String nodeTypeName;

    public LineageNodeType() {
    }

    public LineageNodeType(Integer nodeTypeId, String nodeTypeName) {
       this.nodeTypeId = nodeTypeId;
       this.nodeTypeName = nodeTypeName;
    }
   
     @Id 
    
    @Column(name="NODE_TYPE_ID", unique=true, nullable=false)
    public Integer getNodeTypeId() {
        return this.nodeTypeId;
    }
    
    public void setNodeTypeId(Integer nodeTypeId) {
        this.nodeTypeId = nodeTypeId;
    }
    
    @Column(name="NODE_TYPE_NAME", nullable=false, length=45)
    public String getNodeTypeName() {
        return this.nodeTypeName;
    }
    
    public void setNodeTypeName(String nodeTypeName) {
        this.nodeTypeName = nodeTypeName;
    }




}


