package com.wipro.ats.bdre.md.setup.beans;
// Generated Dec 21, 2015 11:26:14 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LineageNodeType generated by hbm2java
 */
@Entity
@Table(name="LINEAGE_NODE_TYPE"
    ,schema="BDRE"
    ,catalog="BDRE"
)
public class LineageNodeType  implements java.io.Serializable {


     private Integer nodeTypeId;
     private String nodeTypeName;

    public LineageNodeType() {
    }

    public LineageNodeType(Integer nodeTypeId, String nodeTypeName) {
       this.nodeTypeId = nodeTypeId;
       this.nodeTypeName = nodeTypeName;
    }
   
     @Id 
    
    @Column(name="NODE_TYPE_ID", unique=true, nullable=false)
    public Integer getNodeTypeId() {
        return this.nodeTypeId;
    }
    
    public void setNodeTypeId(Integer nodeTypeId) {
        this.nodeTypeId = nodeTypeId;
    }
    
    @Column(name="NODE_TYPE_NAME", nullable=false, length=45)
    public String getNodeTypeName() {
        return this.nodeTypeName;
    }
    
    public void setNodeTypeName(String nodeTypeName) {
        this.nodeTypeName = nodeTypeName;
    }




}


