/*
 * Copyright 2015 Wipro Limited
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.wipro.ats.bdre.md.setup.beans;
// Generated Dec 21, 2015 11:26:14 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;/*
 * Copyright 2015 Wipro Limited
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/**
 * LineageQueryType generated by hbm2java
 */
@Entity
@Table(name="LINEAGE_QUERY_TYPE"

)
public class LineageQueryType  implements java.io.Serializable {


     private Integer queryTypeId;
     private String queryTypeName;

    public LineageQueryType() {
    }

    public LineageQueryType(Integer queryTypeId, String queryTypeName) {
       this.queryTypeId = queryTypeId;
       this.queryTypeName = queryTypeName;
    }
   
     @Id 
    
    @Column(name="QUERY_TYPE_ID", unique=true, nullable=false)
    public Integer getQueryTypeId() {
        return this.queryTypeId;
    }
    
    public void setQueryTypeId(Integer queryTypeId) {
        this.queryTypeId = queryTypeId;
    }
    
    @Column(name="QUERY_TYPE_NAME", nullable=false)
    public String getQueryTypeName() {
        return this.queryTypeName;
    }
    
    public void setQueryTypeName(String queryTypeName) {
        this.queryTypeName = queryTypeName;
    }




}


