package com.wipro.ats.bdre.md.setup.beans;
// Generated Dec 21, 2015 11:26:14 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.Date;

/**
 * LineageNode generated by hbm2java
 */
@Entity
@Table(name="LINEAGE_NODE"
    ,schema="BDRE"
    ,catalog="BDRE"
)
public class LineageNode  implements java.io.Serializable {


     private String nodeId;
     private Integer nodeTypeId;
     private String containerNodeId;
     private Integer nodeOrder;
     private Date insertTs;
     private Date updateTs;
     private String dotString;
     private String dotLabel;
     private String displayName;

    public LineageNode() {
    }

	
    public LineageNode(String nodeId, Integer nodeTypeId, Date insertTs) {
        this.nodeId = nodeId;
        this.nodeTypeId = nodeTypeId;
        this.insertTs = insertTs;
    }
    public LineageNode(String nodeId, Integer nodeTypeId, String containerNodeId, Integer nodeOrder, Date insertTs, Date updateTs, String dotString, String dotLabel, String displayName) {
       this.nodeId = nodeId;
       this.nodeTypeId = nodeTypeId;
       this.containerNodeId = containerNodeId;
       this.nodeOrder = nodeOrder;
       this.insertTs = insertTs;
       this.updateTs = updateTs;
       this.dotString = dotString;
       this.dotLabel = dotLabel;
       this.displayName = displayName;
    }
   
     @Id 
    
    @Column(name="NODE_ID", unique=true, nullable=false, length=100)
    public String getNodeId() {
        return this.nodeId;
    }
    
    public void setNodeId(String nodeId) {
        this.nodeId = nodeId;
    }
    
    @Column(name="NODE_TYPE_ID", nullable=false)
    public Integer getNodeTypeId() {
        return this.nodeTypeId;
    }
    
    public void setNodeTypeId(Integer nodeTypeId) {
        this.nodeTypeId = nodeTypeId;
    }
    
    @Column(name="CONTAINER_NODE_ID", length=100)
    public String getContainerNodeId() {
        return this.containerNodeId;
    }
    
    public void setContainerNodeId(String containerNodeId) {
        this.containerNodeId = containerNodeId;
    }
    
    @Column(name="NODE_ORDER")
    public Integer getNodeOrder() {
        return this.nodeOrder;
    }
    
    public void setNodeOrder(Integer nodeOrder) {
        this.nodeOrder = nodeOrder;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="INSERT_TS", nullable=false, length=23)
    public Date getInsertTs() {
        return this.insertTs;
    }
    
    public void setInsertTs(Date insertTs) {
        this.insertTs = insertTs;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATE_TS", length=23)
    public Date getUpdateTs() {
        return this.updateTs;
    }
    
    public void setUpdateTs(Date updateTs) {
        this.updateTs = updateTs;
    }
    
    @Column(name="DOT_STRING", length=4000)
    public String getDotString() {
        return this.dotString;
    }
    
    public void setDotString(String dotString) {
        this.dotString = dotString;
    }
    
    @Column(name="DOT_LABEL", length=4000)
    public String getDotLabel() {
        return this.dotLabel;
    }
    
    public void setDotLabel(String dotLabel) {
        this.dotLabel = dotLabel;
    }
    
    @Column(name="DISPLAY_NAME", length=256)
    public String getDisplayName() {
        return this.displayName;
    }
    
    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }




}


