package com.wipro.ats.bdre.md.setup.beans;
// Generated Dec 21, 2015 11:26:14 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LineageRelation generated by hbm2java
 */
@Entity
@Table(name="LINEAGE_RELATION"
    ,schema="BDRE"
    ,catalog="BDRE"
)
public class LineageRelation  implements java.io.Serializable {


     private String relationId;
     private String srcNodeId;
     private String targetNodeId;
     private String queryId;
     private String dotString;

    public LineageRelation() {
    }

	
    public LineageRelation(String relationId, String queryId) {
        this.relationId = relationId;
        this.queryId = queryId;
    }
    public LineageRelation(String relationId, String srcNodeId, String targetNodeId, String queryId, String dotString) {
       this.relationId = relationId;
       this.srcNodeId = srcNodeId;
       this.targetNodeId = targetNodeId;
       this.queryId = queryId;
       this.dotString = dotString;
    }
   
     @Id 
    
    @Column(name="RELATION_ID", unique=true, nullable=false, length=100)
    public String getRelationId() {
        return this.relationId;
    }
    
    public void setRelationId(String relationId) {
        this.relationId = relationId;
    }
    
    @Column(name="SRC_NODE_ID", length=100)
    public String getSrcNodeId() {
        return this.srcNodeId;
    }
    
    public void setSrcNodeId(String srcNodeId) {
        this.srcNodeId = srcNodeId;
    }
    
    @Column(name="TARGET_NODE_ID", length=100)
    public String getTargetNodeId() {
        return this.targetNodeId;
    }
    
    public void setTargetNodeId(String targetNodeId) {
        this.targetNodeId = targetNodeId;
    }
    
    @Column(name="QUERY_ID", nullable=false, length=100)
    public String getQueryId() {
        return this.queryId;
    }
    
    public void setQueryId(String queryId) {
        this.queryId = queryId;
    }
    
    @Column(name="DOT_STRING", length=4000)
    public String getDotString() {
        return this.dotString;
    }
    
    public void setDotString(String dotString) {
        this.dotString = dotString;
    }




}


