package com.wipro.ats.bdre.md.setup.beans;
// Generated Dec 21, 2015 11:26:14 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Pendingurlsdb generated by hbm2java
 */
@Entity
@Table(name="PENDINGURLSDB"
    ,schema="BDRE"
    ,catalog="BDRE"
)
public class Pendingurlsdb  implements java.io.Serializable {


     private Long uniqid;
     private Long pid;
     private Long instanceexecid;
     private String url;
     private Integer docid;
     private Integer parentdocid;
     private String parenturl;
     private Integer depth;
     private String domain;
     private String subdomain;
     private String path;
     private String anchor;
     private Integer priority;
     private String tag;

    public Pendingurlsdb() {
    }

	
    public Pendingurlsdb(Integer docid, Integer parentdocid, Integer depth, Integer priority) {
        this.docid = docid;
        this.parentdocid = parentdocid;
        this.depth = depth;
        this.priority = priority;
    }
    public Pendingurlsdb(Long pid, Long instanceexecid, String url, Integer docid, Integer parentdocid, String parenturl, Integer depth, String domain, String subdomain, String path, String anchor, Integer priority, String tag) {
       this.pid = pid;
       this.instanceexecid = instanceexecid;
       this.url = url;
       this.docid = docid;
       this.parentdocid = parentdocid;
       this.parenturl = parenturl;
       this.depth = depth;
       this.domain = domain;
       this.subdomain = subdomain;
       this.path = path;
       this.anchor = anchor;
       this.priority = priority;
       this.tag = tag;
    }
   
     @Id 
    
    @Column(name="UNIQID", unique=true, nullable=false)
    public Long getUniqid() {
        return this.uniqid;
    }
    
    public void setUniqid(Long uniqid) {
        this.uniqid = uniqid;
    }
    
    @Column(name="PID")
    public Long getPid() {
        return this.pid;
    }
    
    public void setPid(Long pid) {
        this.pid = pid;
    }
    
    @Column(name="INSTANCEEXECID")
    public Long getInstanceexecid() {
        return this.instanceexecid;
    }
    
    public void setInstanceexecid(Long instanceexecid) {
        this.instanceexecid = instanceexecid;
    }
    
    @Column(name="URL", length=3000)
    public String getUrl() {
        return this.url;
    }
    
    public void setUrl(String url) {
        this.url = url;
    }
    
    @Column(name="DOCID", nullable=false)
    public Integer getDocid() {
        return this.docid;
    }
    
    public void setDocid(Integer docid) {
        this.docid = docid;
    }
    
    @Column(name="PARENTDOCID", nullable=false)
    public Integer getParentdocid() {
        return this.parentdocid;
    }
    
    public void setParentdocid(Integer parentdocid) {
        this.parentdocid = parentdocid;
    }
    
    @Column(name="PARENTURL", length=1000)
    public String getParenturl() {
        return this.parenturl;
    }
    
    public void setParenturl(String parenturl) {
        this.parenturl = parenturl;
    }
    
    @Column(name="DEPTH", nullable=false)
    public Integer getDepth() {
        return this.depth;
    }
    
    public void setDepth(Integer depth) {
        this.depth = depth;
    }
    
    @Column(name="DOMAIN")
    public String getDomain() {
        return this.domain;
    }
    
    public void setDomain(String domain) {
        this.domain = domain;
    }
    
    @Column(name="SUBDOMAIN")
    public String getSubdomain() {
        return this.subdomain;
    }
    
    public void setSubdomain(String subdomain) {
        this.subdomain = subdomain;
    }
    
    @Column(name="PATH", length=1000)
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }
    
    @Column(name="ANCHOR")
    public String getAnchor() {
        return this.anchor;
    }
    
    public void setAnchor(String anchor) {
        this.anchor = anchor;
    }
    
    @Column(name="PRIORITY", nullable=false)
    public Integer getPriority() {
        return this.priority;
    }
    
    public void setPriority(Integer priority) {
        this.priority = priority;
    }
    
    @Column(name="TAG")
    public String getTag() {
        return this.tag;
    }
    
    public void setTag(String tag) {
        this.tag = tag;
    }




}


