package com.wipro.ats.bdre.md.setup.beans;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
/**
 * PermissionType generated by hbm2java
 */
@Entity
@Table(name="PERMISSION_TYPE"
)
public class PermissionType  implements java.io.Serializable {


    private Integer permissionTypeId;
    private String permissionTypeName;

    public PermissionType() {
    }

    public PermissionType(Integer permissionTypeId, String permissionTypeName) {
        this.permissionTypeId = permissionTypeId;
        this.permissionTypeName = permissionTypeName;
    }

    @Id

    @Column(name="PERMISSION_TYPE_ID", unique=true, nullable=false)
    public Integer getPermissionTypeId() {
        return this.permissionTypeId;
    }

    public void setPermissionTypeId(Integer permissionTypeId) {
        this.permissionTypeId = permissionTypeId;
    }

    @Column(name="PERMISSION_TYPE_NAME", nullable=false, length=45)
    public String getPermissionTypeName() {
        return this.permissionTypeName;
    }

    public void setPermissionTypeName(String permissionTypeName) {
        this.permissionTypeName = permissionTypeName;
    }




}


