package com.wipro.ats.bdre.md.setup.beans;
// Generated Dec 21, 2015 11:26:14 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.Date;

/**
 * ProcessDeploymentQueue generated by hbm2java
 */
@Entity
@Table(name="PROCESS_DEPLOYMENT_QUEUE"
    ,schema="BDRE"
    ,catalog="BDRE"
)
public class ProcessDeploymentQueue  implements java.io.Serializable {


     private Long deploymentId;
     private Integer processId;
     private Date startTs;
     private Date insertTs;
     private Date endTs;
     private Short deployStatusId;
     private String userName;
     private Integer busDomainId;
     private Integer processTypeId;
     private String deployScriptLocation;

    public ProcessDeploymentQueue() {
    }

	
    public ProcessDeploymentQueue(Integer processId, Date insertTs, Short deployStatusId, String userName, Integer busDomainId, Integer processTypeId) {
        this.processId = processId;
        this.insertTs = insertTs;
        this.deployStatusId = deployStatusId;
        this.userName = userName;
        this.busDomainId = busDomainId;
        this.processTypeId = processTypeId;
    }
    public ProcessDeploymentQueue(Integer processId, Date startTs, Date insertTs, Date endTs, Short deployStatusId, String userName, Integer busDomainId, Integer processTypeId, String deployScriptLocation) {
       this.processId = processId;
       this.startTs = startTs;
       this.insertTs = insertTs;
       this.endTs = endTs;
       this.deployStatusId = deployStatusId;
       this.userName = userName;
       this.busDomainId = busDomainId;
       this.processTypeId = processTypeId;
       this.deployScriptLocation = deployScriptLocation;
    }
   
     @Id 
    
    @Column(name="DEPLOYMENT_ID", unique=true, nullable=false)
    public Long getDeploymentId() {
        return this.deploymentId;
    }
    
    public void setDeploymentId(Long deploymentId) {
        this.deploymentId = deploymentId;
    }
    
    @Column(name="PROCESS_ID", nullable=false)
    public Integer getProcessId() {
        return this.processId;
    }
    
    public void setProcessId(Integer processId) {
        this.processId = processId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="START_TS", length=23)
    public Date getStartTs() {
        return this.startTs;
    }
    
    public void setStartTs(Date startTs) {
        this.startTs = startTs;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="INSERT_TS", nullable=false, length=23)
    public Date getInsertTs() {
        return this.insertTs;
    }
    
    public void setInsertTs(Date insertTs) {
        this.insertTs = insertTs;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="END_TS", length=23)
    public Date getEndTs() {
        return this.endTs;
    }
    
    public void setEndTs(Date endTs) {
        this.endTs = endTs;
    }
    
    @Column(name="DEPLOY_STATUS_ID", nullable=false)
    public Short getDeployStatusId() {
        return this.deployStatusId;
    }
    
    public void setDeployStatusId(Short deployStatusId) {
        this.deployStatusId = deployStatusId;
    }
    
    @Column(name="USER_NAME", nullable=false, length=45)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    
    @Column(name="BUS_DOMAIN_ID", nullable=false)
    public Integer getBusDomainId() {
        return this.busDomainId;
    }
    
    public void setBusDomainId(Integer busDomainId) {
        this.busDomainId = busDomainId;
    }
    
    @Column(name="PROCESS_TYPE_ID", nullable=false)
    public Integer getProcessTypeId() {
        return this.processTypeId;
    }
    
    public void setProcessTypeId(Integer processTypeId) {
        this.processTypeId = processTypeId;
    }
    
    @Column(name="DEPLOY_SCRIPT_LOCATION", length=1000)
    public String getDeployScriptLocation() {
        return this.deployScriptLocation;
    }
    
    public void setDeployScriptLocation(String deployScriptLocation) {
        this.deployScriptLocation = deployScriptLocation;
    }




}


