package com.wipro.ats.bdre.md.setup.beans;
// Generated Dec 21, 2015 11:26:14 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.Date;

/**
 * ProcessLog generated by hbm2java
 */
@Entity
@Table(name="PROCESS_LOG"
    ,schema="BDRE"
    ,catalog="BDRE"
)
public class ProcessLog  implements java.io.Serializable {


     private Long logId;
     private Date addTs;
     private Integer processId;
     private String logCategory;
     private String messageId;
     private String message;
     private Long instanceRef;

    public ProcessLog() {
    }

	
    public ProcessLog(Integer processId, String logCategory, String messageId, String message) {
        this.processId = processId;
        this.logCategory = logCategory;
        this.messageId = messageId;
        this.message = message;
    }
    public ProcessLog(Date addTs, Integer processId, String logCategory, String messageId, String message, Long instanceRef) {
       this.addTs = addTs;
       this.processId = processId;
       this.logCategory = logCategory;
       this.messageId = messageId;
       this.message = message;
       this.instanceRef = instanceRef;
    }
   
     @Id 
    
    @Column(name="LOG_ID", unique=true, nullable=false)
    public Long getLogId() {
        return this.logId;
    }
    
    public void setLogId(Long logId) {
        this.logId = logId;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ADD_TS", length=23)
    public Date getAddTs() {
        return this.addTs;
    }
    
    public void setAddTs(Date addTs) {
        this.addTs = addTs;
    }
    
    @Column(name="PROCESS_ID", nullable=false)
    public Integer getProcessId() {
        return this.processId;
    }
    
    public void setProcessId(Integer processId) {
        this.processId = processId;
    }
    
    @Column(name="LOG_CATEGORY", nullable=false, length=10)
    public String getLogCategory() {
        return this.logCategory;
    }
    
    public void setLogCategory(String logCategory) {
        this.logCategory = logCategory;
    }
    
    @Column(name="MESSAGE_ID", nullable=false, length=128)
    public String getMessageId() {
        return this.messageId;
    }
    
    public void setMessageId(String messageId) {
        this.messageId = messageId;
    }
    
    @Column(name="MESSAGE", nullable=false, length=1024)
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }
    
    @Column(name="INSTANCE_REF")
    public Long getInstanceRef() {
        return this.instanceRef;
    }
    
    public void setInstanceRef(Long instanceRef) {
        this.instanceRef = instanceRef;
    }




}


