/*
 * Copyright 2015 Wipro Limited
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.wipro.ats.bdre.md.setup.beans;
// Generated Dec 21, 2015 11:26:14 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;
import java.util.Date;

/**
 * ProcessTemplate generated by hbm2java
 */
@Entity
@Table(name="PROCESS_TEMPLATE"

)
public class ProcessTemplate  implements java.io.Serializable {


     private Integer processTemplateId;
     private String description;
     private Date addTs;
     private String processName;
     private Integer busDomainId;
     private Integer processTypeId;
     private Integer parentProcessId;
     private Boolean canRecover;
     private String batchCutPattern;
     private String nextProcessTemplateId;
     private Boolean deleteFlag;
     private Integer workflowId;

    public ProcessTemplate() {
    }

	
    public ProcessTemplate(String description, Date addTs, String processName, Integer busDomainId, Integer processTypeId, Boolean canRecover, String nextProcessTemplateId, Boolean deleteFlag) {
        this.description = description;
        this.addTs = addTs;
        this.processName = processName;
        this.busDomainId = busDomainId;
        this.processTypeId = processTypeId;
        this.canRecover = canRecover;
        this.nextProcessTemplateId = nextProcessTemplateId;
        this.deleteFlag = deleteFlag;
    }
    public ProcessTemplate(String description, Date addTs, String processName, Integer busDomainId, Integer processTypeId, Integer parentProcessId, Boolean canRecover, String batchCutPattern, String nextProcessTemplateId, Boolean deleteFlag, Integer workflowId) {
       this.description = description;
       this.addTs = addTs;
       this.processName = processName;
       this.busDomainId = busDomainId;
       this.processTypeId = processTypeId;
       this.parentProcessId = parentProcessId;
       this.canRecover = canRecover;
       this.batchCutPattern = batchCutPattern;
       this.nextProcessTemplateId = nextProcessTemplateId;
       this.deleteFlag = deleteFlag;
       this.workflowId = workflowId;
    }
   
     @Id 
    
    @Column(name="PROCESS_TEMPLATE_ID", unique=true, nullable=false)
    public Integer getProcessTemplateId() {
        return this.processTemplateId;
    }
    
    public void setProcessTemplateId(Integer processTemplateId) {
        this.processTemplateId = processTemplateId;
    }
    
    @Column(name="DESCRIPTION", nullable=false, length=256)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="ADD_TS", nullable=false, length=23)
    public Date getAddTs() {
        return this.addTs;
    }
    
    public void setAddTs(Date addTs) {
        this.addTs = addTs;
    }
    
    @Column(name="PROCESS_NAME", nullable=false, length=45)
    public String getProcessName() {
        return this.processName;
    }
    
    public void setProcessName(String processName) {
        this.processName = processName;
    }
    
    @Column(name="BUS_DOMAIN_ID", nullable=false)
    public Integer getBusDomainId() {
        return this.busDomainId;
    }
    
    public void setBusDomainId(Integer busDomainId) {
        this.busDomainId = busDomainId;
    }
    
    @Column(name="PROCESS_TYPE_ID", nullable=false)
    public Integer getProcessTypeId() {
        return this.processTypeId;
    }
    
    public void setProcessTypeId(Integer processTypeId) {
        this.processTypeId = processTypeId;
    }
    
    @Column(name="PARENT_PROCESS_ID")
    public Integer getParentProcessId() {
        return this.parentProcessId;
    }
    
    public void setParentProcessId(Integer parentProcessId) {
        this.parentProcessId = parentProcessId;
    }
    
    @Column(name="CAN_RECOVER", nullable=false)
    public Boolean getCanRecover() {
        return this.canRecover;
    }
    
    public void setCanRecover(Boolean canRecover) {
        this.canRecover = canRecover;
    }
    
    @Column(name="BATCH_CUT_PATTERN", length=45)
    public String getBatchCutPattern() {
        return this.batchCutPattern;
    }
    
    public void setBatchCutPattern(String batchCutPattern) {
        this.batchCutPattern = batchCutPattern;
    }
    
    @Column(name="NEXT_PROCESS_TEMPLATE_ID", nullable=false, length=256)
    public String getNextProcessTemplateId() {
        return this.nextProcessTemplateId;
    }
    
    public void setNextProcessTemplateId(String nextProcessTemplateId) {
        this.nextProcessTemplateId = nextProcessTemplateId;
    }
    
    @Column(name="DELETE_FLAG", nullable=false)
    public Boolean getDeleteFlag() {
        return this.deleteFlag;
    }
    
    public void setDeleteFlag(Boolean deleteFlag) {
        this.deleteFlag = deleteFlag;
    }
    
    @Column(name="WORKFLOW_ID")
    public Integer getWorkflowId() {
        return this.workflowId;
    }
    
    public void setWorkflowId(Integer workflowId) {
        this.workflowId = workflowId;
    }




}


