/*
 * Copyright 2015 Wipro Limited
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.wipro.ats.bdre.md.setup.beans;
// Generated Dec 21, 2015 11:26:14 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * ProcessType generated by hbm2java
 */
@Entity
@Table(name="PROCESS_TYPE"

)
public class ProcessType  implements java.io.Serializable {


     private Integer processTypeId;
     private String processTypeName;
     private Integer parentProcessTypeId;

    public ProcessType() {
    }

	
    public ProcessType(Integer processTypeId, String processTypeName) {
        this.processTypeId = processTypeId;
        this.processTypeName = processTypeName;
    }
    public ProcessType(Integer processTypeId, String processTypeName, Integer parentProcessTypeId) {
       this.processTypeId = processTypeId;
       this.processTypeName = processTypeName;
       this.parentProcessTypeId = parentProcessTypeId;
    }
   
     @Id 
    
    @Column(name="PROCESS_TYPE_ID", unique=true, nullable=false)
    public Integer getProcessTypeId() {
        return this.processTypeId;
    }
    
    public void setProcessTypeId(Integer processTypeId) {
        this.processTypeId = processTypeId;
    }
    
    @Column(name="PROCESS_TYPE_NAME", nullable=false, length=45)
    public String getProcessTypeName() {
        return this.processTypeName;
    }
    
    public void setProcessTypeName(String processTypeName) {
        this.processTypeName = processTypeName;
    }
    
    @Column(name="PARENT_PROCESS_TYPE_ID")
    public Integer getParentProcessTypeId() {
        return this.parentProcessTypeId;
    }
    
    public void setParentProcessTypeId(Integer parentProcessTypeId) {
        this.parentProcessTypeId = parentProcessTypeId;
    }




}


