package com.wipro.ats.bdre.md.setup.beans;
// Generated Dec 21, 2015 11:26:14 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.*;

/**
 * PropertiesTemplate generated by hbm2java
 */
@Entity
@Table(name="PROPERTIES_TEMPLATE"
    ,schema="BDRE"
    ,catalog="BDRE"
)
public class PropertiesTemplate  implements java.io.Serializable {


     private PropertiesTemplateId id;
     private String configGroup;
     private String propTempValue;
     private String description;

    public PropertiesTemplate() {
    }

    public PropertiesTemplate(PropertiesTemplateId id, String configGroup, String propTempValue, String description) {
       this.id = id;
       this.configGroup = configGroup;
       this.propTempValue = propTempValue;
       this.description = description;
    }
   
     @EmbeddedId
    
    @AttributeOverrides( {
        @AttributeOverride(name="processTemplateId", column=@Column(name="PROCESS_TEMPLATE_ID", nullable=false) ), 
        @AttributeOverride(name="propTempKey", column=@Column(name="PROP_TEMP_KEY", nullable=false, length=128) ) } )
    public PropertiesTemplateId getId() {
        return this.id;
    }
    
    public void setId(PropertiesTemplateId id) {
        this.id = id;
    }
    
    @Column(name="CONFIG_GROUP", nullable=false, length=10)
    public String getConfigGroup() {
        return this.configGroup;
    }
    
    public void setConfigGroup(String configGroup) {
        this.configGroup = configGroup;
    }
    
    @Column(name="PROP_TEMP_VALUE", nullable=false, length=2048)
    public String getPropTempValue() {
        return this.propTempValue;
    }
    
    public void setPropTempValue(String propTempValue) {
        this.propTempValue = propTempValue;
    }
    
    @Column(name="DESCRIPTION", nullable=false, length=1028)
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }




}


