package com.wipro.ats.bdre.md.setup.beans;
// Generated Dec 21, 2015 11:26:14 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Statisticsdb generated by hbm2java
 */
@Entity
@Table(name="STATISTICSDB"
    ,schema="BDRE"
    ,catalog="BDRE"
)
public class Statisticsdb  implements java.io.Serializable {


     private Long uniqid;
     private Long value;
     private String name;

    public Statisticsdb() {
    }

    public Statisticsdb(Long value, String name) {
       this.value = value;
       this.name = name;
    }
   
     @Id 
    
    @Column(name="UNIQID", unique=true, nullable=false)
    public Long getUniqid() {
        return this.uniqid;
    }
    
    public void setUniqid(Long uniqid) {
        this.uniqid = uniqid;
    }
    
    @Column(name="VALUE")
    public Long getValue() {
        return this.value;
    }
    
    public void setValue(Long value) {
        this.value = value;
    }
    
    @Column(name="NAME")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


