/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.wipro.ats.bdre.md.setup.beans;
// Generated Dec 21, 2015 11:26:14 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WorkflowType generated by hbm2java
 */
@Entity
@Table(name="WORKFLOW_TYPE"

)
public class WorkflowType  implements java.io.Serializable {


     private Integer workflowId;
     private String workflowTypeName;

    public WorkflowType() {
    }

    public WorkflowType(Integer workflowId, String workflowTypeName) {
       this.workflowId = workflowId;
       this.workflowTypeName = workflowTypeName;
    }
   
     @Id 
    
    @Column(name="WORKFLOW_ID", unique=true, nullable=false)
    public Integer getWorkflowId() {
        return this.workflowId;
    }
    
    public void setWorkflowId(Integer workflowId) {
        this.workflowId = workflowId;
    }
    
    @Column(name="WORKFLOW_TYPE_NAME", nullable=false, length=45)
    public String getWorkflowTypeName() {
        return this.workflowTypeName;
    }
    
    public void setWorkflowTypeName(String workflowTypeName) {
        this.workflowTypeName = workflowTypeName;
    }




}


