package com.wipro.ats.bdre.md.setup.beans;
// Generated Dec 21, 2015 11:26:14 PM by Hibernate Tools 3.2.2.GA


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * WorkflowType generated by hbm2java
 */
@Entity
@Table(name="WORKFLOW_TYPE"
    ,schema="BDRE"
    ,catalog="BDRE"
)
public class WorkflowType  implements java.io.Serializable {


     private Integer workflowId;
     private String workflowTypeName;

    public WorkflowType() {
    }

    public WorkflowType(Integer workflowId, String workflowTypeName) {
       this.workflowId = workflowId;
       this.workflowTypeName = workflowTypeName;
    }
   
     @Id 
    
    @Column(name="WORKFLOW_ID", unique=true, nullable=false)
    public Integer getWorkflowId() {
        return this.workflowId;
    }
    
    public void setWorkflowId(Integer workflowId) {
        this.workflowId = workflowId;
    }
    
    @Column(name="WORKFLOW_TYPE_NAME", nullable=false, length=45)
    public String getWorkflowTypeName() {
        return this.workflowTypeName;
    }
    
    public void setWorkflowTypeName(String workflowTypeName) {
        this.workflowTypeName = workflowTypeName;
    }




}


