/*
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package com.wipro.ats.bdre.md.util;
import com.wipro.ats.bdre.BaseStructure;
import com.wipro.ats.bdre.md.api.GetGeneralConfig;
import com.wipro.ats.bdre.md.beans.table.GeneralConfig;
import org.apache.commons.cli.CommandLine;
import org.apache.log4j.Logger;
import java.io.FileOutputStream;
import java.io.IOException;
import java.util.List;
import java.util.Properties;

/**
 * Created by AR288503 on 12/26/2015.
 */
public class DumpConfigMain extends BaseStructure{
    //Created a dummy PARAMS_STRUCTURE variable to get the environment value.
    private static final String[][] PARAMS_STRUCTURE = {
            {"cg", "config-group", "Config group to dump"},
            {"f", "output-file", "Output file path"},
    };

    private static final Logger LOGGER = Logger.getLogger(DumpConfigMain.class);
    public static void main(String[] args) throws IOException {
        new DumpConfigMain().execute(args);
    }
    public void execute(String[] args) throws IOException {
        CommandLine commandLine = getCommandLine(args, PARAMS_STRUCTURE);
        String cg=commandLine.getOptionValue("cg");
        String outputFile=commandLine.getOptionValue("f");
        LOGGER.info("Config-grp="+cg);
        LOGGER.info("file output="+outputFile);
        GetGeneralConfig ggc = new GetGeneralConfig();
        List<GeneralConfig> gcs = ggc.byConigGroupOnly(cg, 1);
        Properties properties=new Properties();
        FileOutputStream fileOutputStream = new FileOutputStream(outputFile);
        for (GeneralConfig gc: gcs){
            LOGGER.info("gc.getKey()="+gc.getKey()+" gc.getDefaultVal()="+gc.getDefaultVal());
            properties.put(gc.getKey(), gc.getDefaultVal());
        }
        properties.store(fileOutputStream,"Generated by gen config dumper");
        LOGGER.info("Stored properties= "+properties);
    }
}
